# .streamlit/secrets.toml

[api]
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwdHNsdmpzYmhteHBvc3FhcndqIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0NzA1NzQ5MywiZXhwIjoyMDYyNjMzNDkzfQ.9jjjRIXCXdCVvQFSkAqJlJ0cLCiEzFkaCCFE7F02sWQ"
